# Generated by Django 6.0.2 on 2026-05-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='steam_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
