# Generated by Django 6.0.2 on 2026-05-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
